// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGZL8ld_cQeVVFCpM9DmCD8hAzq17m29s',
    appId: '1:1094457100361:web:803e3208efdd1a8765d798',
    messagingSenderId: '1094457100361',
    projectId: 'bloggingproject-37126',
    authDomain: 'bloggingproject-37126.firebaseapp.com',
    storageBucket: 'bloggingproject-37126.firebasestorage.app',
    measurementId: 'G-337Y5771BD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgPpgmp1dSiRyQS6B9EEolQkt-MHtpM6Q',
    appId: '1:1094457100361:android:ae53a13b13b40f0565d798',
    messagingSenderId: '1094457100361',
    projectId: 'bloggingproject-37126',
    storageBucket: 'bloggingproject-37126.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZsjgczbzNl3JJt5z98TL7JY-rb2Z3Ses',
    appId: '1:1094457100361:ios:e83cda766bf6459365d798',
    messagingSenderId: '1094457100361',
    projectId: 'bloggingproject-37126',
    storageBucket: 'bloggingproject-37126.firebasestorage.app',
    iosBundleId: 'com.techslave.techslave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZsjgczbzNl3JJt5z98TL7JY-rb2Z3Ses',
    appId: '1:1094457100361:ios:e83cda766bf6459365d798',
    messagingSenderId: '1094457100361',
    projectId: 'bloggingproject-37126',
    storageBucket: 'bloggingproject-37126.firebasestorage.app',
    iosBundleId: 'com.techslave.techslave',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGZL8ld_cQeVVFCpM9DmCD8hAzq17m29s',
    appId: '1:1094457100361:web:fc5c67ab388bbd7a65d798',
    messagingSenderId: '1094457100361',
    projectId: 'bloggingproject-37126',
    authDomain: 'bloggingproject-37126.firebaseapp.com',
    storageBucket: 'bloggingproject-37126.firebasestorage.app',
    measurementId: 'G-4V6F9EGBTG',
  );

}